"""
Live odds fetcher using The Odds API.
Fetches Asian Handicap (spreads) and Over/Under (totals) odds
from Bet365 and Pinnacle for supported leagues.
"""
import os
import requests
from datetime import datetime
from database import get_connection

ODDS_API_KEY = os.environ.get('ODDS_API_KEY', '')
ODDS_BASE_URL = 'https://api.the-odds-api.com/v4'

# Map our league codes to The Odds API sport keys
LEAGUE_TO_SPORT = {
    'Ligue_1': 'soccer_france_ligue_one',
    'Ligue_2': 'soccer_france_ligue_two',
    'La_Liga': 'soccer_spain_la_liga',
    'La_Liga_2': 'soccer_spain_segunda_division',
    # New leagues
    'Eredivisie': 'soccer_netherlands_eredivisie',
    'Belgium_Pro': 'soccer_belgium_first_div',
    'EPL': 'soccer_epl',
    'Championship': 'soccer_efl_champ',
    'Bundesliga': 'soccer_germany_bundesliga',
    'Bundesliga_2': 'soccer_germany_bundesliga2',
    'Brazil_A': 'soccer_brazil_campeonato',
    'Argentina_A': 'soccer_argentina_primera_division',
    'Chile_A': 'soccer_chile_campeonato',
    'Mexico_A': 'soccer_mexico_ligamx',
    'MLS': 'soccer_usa_mls',
    'KLeague_1': 'soccer_korea_kleague1',
    'JLeague_1': 'soccer_japan_j_league',
}

# League names in Traditional Chinese
LEAGUE_NAMES_ZH = {
    'Ligue_1': '法國甲組聯賽',
    'Ligue_2': '法國乙組聯賽',
    'La_Liga': '西班牙甲組聯賽',
    'La_Liga_2': '西班牙乙組聯賽',
    'Eredivisie': '荷蘭甲組聯賽',
    'Belgium_Pro': '比利時甲組聯賽',
    'EPL': '英格蘭超級聯賽',
    'Championship': '英格蘭冠軍聯賽',
    'Bundesliga': '德國甲組聯賽',
    'Bundesliga_2': '德國乙組聯賽',
    'Brazil_A': '巴西甲組聯賽',
    'Argentina_A': '阿根廷甲組聯賽',
    'Chile_A': '智利甲組聯賽',
    'Mexico_A': '墨西哥超級聯賽',
    'MLS': '美國職業聯賽',
    'KLeague_1': '南韓職業聯賽',
    'JLeague_1': '日本職業聯賽',
}

# Leagues supported by The Odds API but with NO historical data source
# (K League 2 and J2 League have no free historical CSV and no odds API coverage)
LEAGUES_UNAVAILABLE = {
    'KLeague_2': '南韓乙組聯賽',
    'JLeague_2': '日本乙組聯賽',
}

# Short team name mappings (The Odds API uses short names)
TEAM_SHORT_ZH = {
    # Ligue 1
    'Paris Saint-Germain': '巴黎聖日耳門',
    'Marseille': '馬賽',
    'Lyon': '里昂',
    'Monaco': '摩納哥',
    'Lille': '里爾',
    'Rennes': '雷恩',
    'Nice': '尼斯',
    'Lens': '朗斯',
    'Strasbourg': '斯特拉斯堡',
    'Toulouse': '圖盧茲',
    'Lorient': '羅連安特',
    'Le Havre': '勒阿弗爾',
    'Brest': '比斯特',
    'Angers': '昂熱',
    'Auxerre': '歐塞爾',
    'Le Mans': '勒芒',
    'Paris FC': '巴黎足球會',
    'Troyes': '特魯瓦',
    'Montpellier': '蒙彼利埃',
    'Nantes': '南特',
    'Reims': '蘭斯',
    'Saint-Etienne': '聖伊天',    # Ligue 2 (common teams)
    'Metz': '梅斯',
    'Caen': '卡昂',
    'Grenoble': '格勒諾布爾',
    'Guingamp': '甘岡',
    'Sochaux': '索察',
    'Nancy': '南錫',
    'Ajaccio': '阿雅克肖',
    'Bastia': '巴斯蒂亞',
    'Rodez': '羅德茲',
    'Paris': '巴黎足球會',
    'Amiens': '亞眠',
    'Annecy': '安錫',
    'Concarneau': '孔卡爾諾',
    'Dunkerque': '敦刻爾克',
    'Laval': '拉瓦勒',
    'Pau': '波城',
    'Quevilly Rouen': '奎維利魯昂',
    'Rodez Aveyron': '羅德茲',
    'Red Star': '紅星',
    'Toulouse': '圖盧茲',
    # La Liga
    'Real Madrid': '皇家馬德里',
    'Barcelona': '巴塞隆拿',
    'Atletico Madrid': '馬德里體育會',
    'Sevilla': '西維爾',
    'Real Betis': '貝迪斯',
    'Real Sociedad': '皇家蘇斯達',
    'Villarreal': '維拉利爾',
    'Athletic Club': '畢爾包',
    'Valencia': '華倫西亞',
    'Celta Vigo': '切爾達',
    'Espanyol': '愛斯賓奴',
    'Getafe': '基達菲',
    'Osasuna': '奧沙辛拿',
    'Rayo Vallecano': '華歷簡奴',
    'Alaves': '艾拉維斯',
    'Girona': '基羅納',
    'Leganes': '雷加利斯',
    'Mallorca': '馬略卡',
    'Las Palmas': '拉斯彭馬斯',
    'Valladolid': '華拉度列',
    'Elche': '艾爾切',
    'Levante': '利雲特',
    'Malaga': '馬拉加',
    'Racing Santander': '桑坦德競賽',
    'Deportivo La Coruna': '拉科魯尼亞',
    'Zaragoza': '薩拉戈薩',
    'Oviedo': '奧維耶多',
    'Tenerife': '特內里費',
    'Eibar': '伊巴',
    'Sporting Gijon': '希杭',
    'Mirandes': '米蘭迪斯',
    'Cartagena': '卡塔赫納',
    'Burgos': '布爾戈斯',
    'Alcorcon': '阿爾科爾孔',
    'Cordoba': '科爾多瓦',
    'Eldense': '埃爾登斯',
    'Huesca': '侯爾斯卡',
    'Castellon': '卡斯特利翁',
    'Cadiz': '卡迪斯',
    'Sabadell': '薩巴德爾',
    'Almeria': '艾美利亞',
    'Numancia': '紐文西亞',
    'Granada': '格蘭納達',
    'Real Oviedo': '奧維耶多',
    'CD Leganes': '雷加利斯',
    'Real Valladolid': '華拉度列',
    'UD Las Palmas': '拉斯彭馬斯',
    'RCD Mallorca': '馬略卡',
    'RCD Espanyol': '愛斯賓奴',
    'Deportivo Alaves': '艾拉維斯',
    'CA Osasuna': '奧沙辛拿',
    'Valencia CF': '華倫西亞',
    'Sevilla FC': '西維爾',
    'Real Sociedad': '皇家蘇斯達',
    'Athletic Bilbao': '畢爾包',
    'Real Betis': '貝迪斯',
    'Villarreal CF': '維拉利爾',
    'Atletico de Madrid': '馬德里體育會',
    'Celta de Vigo': '切爾達',
    # Additional names from The Odds API
    'AD Ceuta FC': '施奧達',
    'AS Monaco': '摩納哥',
    'Alavés': '艾拉維斯',
    'Albacete': '阿爾巴塞特',
    'Almería': '艾美利亞',
    'Andorra CF': '安道爾',
    'Annecy FC': '安錫',
    'Atlético Madrid': '馬德里體育會',
    'Boulogne': '布洛涅',
    'Burgos CF': '布爾戈斯',
    'CD Castellón': '卡斯特利翁',
    'CD Eldense': '埃爾登斯',
    'Celta Fortuna': '切爾達B隊',
    'Clermont': '克萊蒙',
    'Cádiz CF': '卡迪斯',
    'Córdoba': '科爾多瓦',
    'Deportivo La Coruña': '拉科魯尼亞',
    'Dijon': '第戎',
    'Elche CF': '艾爾切',
    'Girona FC': '基羅納',
    'Granada CF': '格蘭納達',
    'Le Mans FC': '勒芒',
    'Leganés': '雷加利斯',
    'Málaga': '馬拉加',
    'Paris Saint Germain': '巴黎聖日耳門',
    'Pau FC': '波城',
    'RC Lens': '朗斯',
    'Real Racing Club de Santander': '桑坦德競賽',
    'Real Sociedad B': '皇家蘇斯達B隊',
    'Real Valladolid CF': '華拉度列',
    'Rodez AF': '羅德茲',
    'SD Eibar': '伊巴',
    'Sabadell FC': '薩巴德爾',
    'Saint Etienne': '聖伊天',
    'Sporting Gijón': '希杭',
    'Stade Lavallois': '拉瓦勒',
    'Stade de Reims': '蘭斯',
    'USL Dunkerque': '敦刻爾克',
    # === Eredivisie (Netherlands) ===
    'Ajax': '阿積士',
    'PSV Eindhoven': '燕豪芬',
    'PSV': '燕豪芬',
    'Feyenoord': '飛燕諾',
    'AZ Alkmaar': '艾克馬亞',
    'AZ': '艾克馬亞',
    'FC Twente': '川迪',
    'Twente': '川迪',
    'FC Utrecht': '烏德勒支',
    'Utrecht': '烏德勒支',
    'SC Heerenveen': '海倫芬',
    'Heerenveen': '海倫芬',
    'Sparta Rotterdam': '鹿特丹斯巴達',
    'FC Groningen': '格羅寧根',
    'Groningen': '格羅寧根',
    'NEC Nijmegen': '奈梅亨',
    'NEC': '奈梅亨',
    'PEC Zwolle': '施禾尼',
    'Zwolle': '施禾尼',
    'Fortuna Sittard': '幸運薛達',
    'Heracles Almelo': '靴迪斯',
    'Heracles': '靴迪斯',
    'RKC Waalwijk': '華域克',
    'Waalwijk': '華域克',
    'Almere City': '阿梅爾城',
    'Go Ahead Eagles': '前進飛鷹',
    'Willem II': '威廉二世',
    'NAC Breda': 'NAC比達',
    'SC Cambuur': '甘堡爾',
    'Cambuur': '甘堡爾',
    'Excelsior': '鹿特丹精英',
    'SBV Excelsior': '鹿特丹精英',
    'Vitesse': '維迪斯',
    'FC Volendam': '禾寧丹',
    'Volendam': '禾寧丹',
    'FC Emmen': '安曼',
    'Emmen': '安曼',
    'De Graafschap': '迪加史卓普',
    'Roda JC': '洛達',
    'MVV Maastricht': '馬斯特里赫特',
    'FC Den Bosch': '丹保殊',
    'Telstar': '泰斯達',
    'TOP Oss': '奧斯',
    'Almere': '阿梅爾城',
    # === Belgium Pro League ===
    'Club Brugge': '布魯日',
    'Club Bruges': '布魯日',
    'Anderlecht': '安德烈治',
    'KRC Genk': '亨克',
    'Genk': '亨克',
    'KAA Gent': '真特',
    'Gent': '真特',
    'Standard Liege': '標準列治',
    'Standard Liège': '標準列治',
    'Royal Antwerp': '安特衛普',
    'Antwerp': '安特衛普',
    'Sporting Charleroi': '查內爾',
    'Charleroi': '查內爾',
    'OH Leuven': '奧特希費利',
    'Oud-Heverlee Leuven': '奧特希費利',
    'Westerlo': '韋斯達路',
    'St Truiden': '聖圖爾登',
    'Sint-Truiden': '聖圖爾登',
    'KV Mechelen': '梅赫倫',
    'Mechelen': '梅赫倫',
    'Cercle Brugge': '布魯日塞克爾',
    'KV Kortrijk': '哥積克',
    'Kortrijk': '哥積克',
    'KAS Eupen': '歐本',
    'Eupen': '歐本',
    'Zulte Waregem': '威爾郡',
    'Dender': '丹達',
    'Beerschot': '比斯查',
    'Union Saint-Gilloise': '聖基萊斯聯',
    'Union SG': '聖基萊斯聯',
    'Royale Union SG': '聖基萊斯聯',
    'Aalst': '阿爾斯特',
    'Lokeren': '洛格倫',
    'KSV Roeselare': '羅斯勒',
    'Waasland-Beveren': '華斯蘭比華倫',
    'Mouscron': '穆斯克龍',
    # === England Premier League ===
    'Arsenal': '阿仙奴',
    'Aston Villa': '阿士東維拉',
    'Bournemouth': '般尼茅夫',
    'Brentford': '賓福特',
    'Brighton': '白禮頓',
    'Burnley': '般尼',
    'Chelsea': '車路士',
    'Crystal Palace': '水晶宮',
    'Everton': '愛華頓',
    'Fulham': '富咸',
    'Leeds United': '列斯聯',
    'Leeds': '列斯聯',
    'Leicester City': '李斯特城',
    'Leicester': '李斯特城',
    'Liverpool': '利物浦',
    'Manchester City': '曼城',
    'Man City': '曼城',
    'Manchester United': '曼聯',
    'Man United': '曼聯',
    'Newcastle United': '紐卡素',
    'Newcastle': '紐卡素',
    'Norwich City': '諾域治',
    'Norwich': '諾域治',
    'Sheffield United': '錫菲聯',
    'Sheff Utd': '錫菲聯',
    'Southampton': '修咸頓',
    'Tottenham': '熱刺',
    'Tottenham Hotspur': '熱刺',
    'Watford': '屈福特',
    'West Bromwich Albion': '西布朗',
    'West Brom': '西布朗',
    'West Ham United': '韋斯咸',
    'West Ham': '韋斯咸',
    'Wolves': '狼隊',
    'Wolverhampton': '狼隊',
    'Wolverhampton Wanderers': '狼隊',
    'Ipswich Town': '葉士域治',
    'Ipswich': '葉士域治',
    'Nottingham Forest': '諾定咸森林',
    "Nott'm Forest": '諾定咸森林',
    'Luton Town': '盧頓',
    'Luton': '盧頓',
    'Sunderland': '新特蘭',
    'Middlesbrough': '米杜士堡',
    'Derby County': '打比郡',
    'Coventry City': '高雲地利',
    'Hull City': '侯城',
    'Stoke City': '史篤城',
    'Swansea City': '史雲斯',
    'Preston North End': '普雷斯頓',
    'Preston': '普雷斯頓',
    'Blackburn Rovers': '布力般流浪',
    'Blackburn': '布力般流浪',
    'Bristol City': '布里斯托城',
    'Cardiff City': '卡迪夫城',
    'Cardiff': '卡迪夫城',
    'QPR': '昆士柏流浪',
    'Queens Park Rangers': '昆士柏流浪',
    'Millwall': '米禾爾',
    'Birmingham City': '伯明翰',
    'Birmingham': '伯明翰',
    'Charlton Athletic': '查爾頓',
    'Portsmouth': '樸茨茅夫',
    'Sheffield Wednesday': '錫周三',
    'Sheff Wed': '錫周三',
    'Wigan Athletic': '韋根',
    'Wigan': '韋根',
    'Reading': '雷丁',
    'Rotherham United': '洛達咸',
    'Rotherham': '洛達咸',
    'Plymouth Argyle': '普利茅夫',
    'Plymouth': '普利茅夫',
    'Oxford United': '牛津聯',
    'Oxford': '牛津聯',
    # === Germany Bundesliga ===
    'Bayern Munich': '拜仁慕尼黑',
    'Bayern München': '拜仁慕尼黑',
    'Borussia Dortmund': '多蒙特',
    'Dortmund': '多蒙特',
    'Bayer Leverkusen': '利華古遜',
    'Leverkusen': '利華古遜',
    'RB Leipzig': 'RB萊比錫',
    'Leipzig': 'RB萊比錫',
    'Eintracht Frankfurt': '法蘭克福',
    'Frankfurt': '法蘭克福',
    'VfL Wolfsburg': '禾夫斯堡',
    'Wolfsburg': '禾夫斯堡',
    'Borussia Monchengladbach': '慕遜加柏',
    'Borussia Mönchengladbach': '慕遜加柏',
    "Borussia M'Gladbach": '慕遜加柏',
    'Gladbach': '慕遜加柏',
    'VfB Stuttgart': '史特加',
    'Stuttgart': '史特加',
    'SC Freiburg': '費雷堡',
    'Freiburg': '費雷堡',
    'TSG Hoffenheim': '賀芬咸',
    'Hoffenheim': '賀芬咸',
    'FSV Mainz 05': '緬恩斯',
    'Mainz 05': '緬恩斯',
    'Mainz': '緬恩斯',
    'FC Augsburg': '奧格斯堡',
    'Augsburg': '奧格斯堡',
    'Werder Bremen': '雲達不萊梅',
    'Bremen': '雲達不萊梅',
    'Union Berlin': '柏林聯',
    'FC Union Berlin': '柏林聯',
    'VfL Bochum': '波琴',
    'Bochum': '波琴',
    '1. FC Heidenheim': '海登咸',
    'Heidenheim': '海登咸',
    'FC St. Pauli': '聖保利',
    'St. Pauli': '聖保利',
    'Holstein Kiel': '基爾',
    "Holstein Kiel'": '基爾',
    'Kiel': '基爾',
    # === Germany Bundesliga 2 ===
    'FC Schalke 04': '史浩克零四',
    'Schalke 04': '史浩克零四',
    'Schalke': '史浩克零四',
    'Hamburger SV': '漢堡',
    'Hamburg': '漢堡',
    'Hertha Berlin': '哈化柏林',
    'Hertha BSC': '哈化柏林',
    '1. FC Kaiserslautern': '凱沙羅頓',
    'Kaiserslautern': '凱沙羅頓',
    '1. FC Nurnberg': '紐倫堡',
    'Nurnberg': '紐倫堡',
    'Nürnberg': '紐倫堡',
    'Hannover 96': '漢諾威',
    'Hannover': '漢諾威',
    'SV Darmstadt 98': '達斯泰特',
    'Darmstadt': '達斯泰特',
    'Karlsruher SC': '卡爾斯魯厄',
    'Karlsruhe': '卡爾斯魯厄',
    'Fortuna Dusseldorf': '杜塞爾多夫',
    'Fortuna Düsseldorf': '杜塞爾多夫',
    'Dusseldorf': '杜塞爾多夫',
    'SC Paderborn 07': '柏達邦',
    'Paderborn': '柏達邦',
    'Greuther Furth': '格雷特霍夫',
    'Greuther Fürth': '格雷特霍夫',
    'Furth': '格雷特霍夫',
    '1. FC Magdeburg': '馬德堡',
    'Magdeburg': '馬德堡',
    'SV Elversberg': '艾華斯堡',
    'Elversberg': '艾華斯堡',
    'Eintracht Braunschweig': '布倫瑞克',
    'Braunschweig': '布倫瑞克',
    'Hansa Rostock': '羅斯托克',
    'Rostock': '羅斯托克',
    'VfL Osnabruck': '奧斯納貝克',
    'Osnabrück': '奧斯納貝克',
    'Osnabruck': '奧斯納貝克',
    'SV Wehen Wiesbaden': '韋恩',
    'Wehen': '韋恩',
    'Preussen Munster': '普斯魯士明斯特',
    'Preußen Münster': '普斯魯士明斯特',
    'SSV Ulm 1846': '烏爾姆',
    'Ulm': '烏爾姆',
    '1. FC Köln': '科隆',
    'FC Koln': '科隆',
    'Köln': '科隆',
    'SC Freiburg II': '費雷堡II隊',
    # === Brazil Serie A ===
    'Flamengo': '法林明高',
    'Palmeiras': '彭美拉斯',
    'Sao Paulo': '聖保羅',
    'São Paulo': '聖保羅',
    'Corinthians': '哥連泰斯',
    'Fluminense': '富明尼斯',
    'Atletico Mineiro': '明尼路',
    'Atlético Mineiro': '明尼路',
    'Gremio': '甘美奧',
    'Grêmio': '甘美奧',
    'Internacional': '國際體育會',
    'Santos': '山度士',
    'Vasco da Gama': '華斯高',
    'Vasco': '華斯高',
    'Botafogo': '保地花高',
    'Athletico Paranaense': '巴拉納體育會',
    'Atletico Paranaense': '巴拉納體育會',
    'RB Bragantino': '巴拉干天奴紅牛',
    'Bragantino': '巴拉干天奴紅牛',
    'Red Bull Bragantino': '巴拉干天奴紅牛',
    'Fortaleza': '福塔雷薩',
    'Ceara': '施亞拉',
    'Ceará': '施亞拉',
    'Bahia': '巴希亞',
    'Cruzeiro': '高士路',
    'Atletico Goianiense': '戈亞尼恩斯',
    'Atlético Goianiense': '戈亞尼恩斯',
    'Juventude': '尤文都德',
    'Cuiaba': '古亞巴',
    'Cuiabá': '古亞巴',
    'America Mineiro': '阿美利加明尼路',
    'América Mineiro': '阿美利加明尼路',
    'Goias': '戈亞斯',
    'Goiás': '戈亞斯',
    'Coritiba': '哥列迪巴',
    'Sport Recife': '累西腓體育',
    'Chapecoense': '查比高恩斯',
    'Avai': '阿瓦伊',
    'Avaí': '阿瓦伊',
    'Ponte Preta': '邦迪比達',
    'Mirassol': '米拉索',
    'Novorizontino': '路禾利桑天奴',
    'Criciuma': '基斯奧馬',
    'Criciúma': '基斯奧馬',
    'Vitoria': '維多利亞',
    'Vitória': '維多利亞',
    'Athletic Club': '阿塞拜疆體育會',
    'Brusque': '布魯斯克',
    'Ituano': '伊圖阿諾',
    'Guarani': '瓜蘭尼',
    'Operario Ferroviario': '費路維亞里奧',
    'Operário Ferroviário': '費路維亞里奧',
    'Tombense': '湯比斯',
    'CRB': 'CRB',
    'Csa': 'CSA',
    'Nautico': '瑙蒂科',
    'Náutico': '瑙蒂科',
    'Sampaio Correa': '桑帕約科雷亞',
    'Vila Nova': '維拉諾瓦',
    'Londrina': '隆德里納',
    'Criciuma': '基斯奧馬',
    # === Argentina Primera Division ===
    'Boca Juniors': '小保加',
    'River Plate': '河床',
    'Racing Club': '競賽會',
    'Racing': '競賽會',
    'Independiente': '獨立隊',
    'San Lorenzo': '聖羅倫素',
    'Estudiantes': '學生隊',
    'Estudiantes LP': '學生隊',
    'Velez Sarsfield': '沙士菲',
    'Vélez Sarsfield': '沙士菲',
    'Velez': '沙士菲',
    "Newell's Old Boys": '紐維爾舊生',
    'Newells Old Boys': '紐維爾舊生',
    'Rosario Central': '羅沙里奧中央',
    'Lanus': '拉努斯',
    'Lanús': '拉努斯',
    'Banfield': '班菲特',
    'Godoy Cruz': '葛度爾古斯',
    'Talleres': '泰拿尼斯',
    'Talleres Cordoba': '泰拿尼斯',
    'Belgrano': '貝格拉諾',
    'Huracan': '颶風隊',
    'Huracán': '颶風隊',
    'Argentinos Juniors': '小阿根廷人',
    'Gimnasia LP': '甘拿斯亞',
    'Gimnasia': '甘拿斯亞',
    'Defensa y Justicia': '防衛者',
    'Arsenal Sarandi': '沙蘭迪兵工廠',
    'Arsenal de Sarandi': '沙蘭迪兵工廠',
    'Colon': '高隆',
    'Colón': '高隆',
    'Union Santa Fe': '聖達菲聯',
    'Unión Santa Fe': '聖達菲聯',
    'Union': '聖達菲聯',
    'Sarmiento': '薩米恩托',
    'Platense': '普拉騰斯',
    'Central Cordoba': '科爾多瓦中央',
    'Central Córdoba': '科爾多瓦中央',
    'Barracas Central': '巴拉斯卡中央',
    'Instituto': '體育學院',
    'Instituto Cordoba': '體育學院',
    'Tigre': '堤格雷',
    'Aldosivi': '阿度斯維',
    'Patronato': '帕托拿圖',
    'Olimpo': '奧林普',
    'Quilmes': '基爾梅斯',
    'All Boys': '全男孩',
    'Temperley': '坦柏利',
    'Chacarita Juniors': '查卡利塔青年',
    'Atlanta': '阿特蘭大',
    'Brown de Adrogue': '阿德罗格布朗',
    'Nueva Chicago': '新芝加哥',
    'Almagro': '阿爾馬格羅',
    'Atlético Rafaela': '拉斐拉競技',
    'Atletico Rafaela': '拉斐拉競技',
    'Boca Unidos': '小保加聯合',
    'Crucero del Norte': '北方十字軍',
    'Defensores de Belgrano': '貝格拉諾防衛者',
    'Deportivo Moron': '莫隆體育',
    'Deportivo Riestra': '列斯特拉體育',
    'Estudiantes de Rio Cuarto': '學生隊里奧誇爾托',
    'Ferro Carril Oeste': '西部鐵路',
    'Gimnasia de Jujuy': '胡胡伊體操',
    'Guillermo Brown': '吉列爾莫布朗',
    'Independiente Rivadavia': '獨立隊里瓦達維亞',
    'Mitre': '米特雷',
    'San Martin de San Juan': '聖馬丁聖胡安',
    'San Martin de Tucuman': '聖馬丁圖庫曼',
    'San Martín de Tucumán': '聖馬丁圖庫曼',
    'Sarmiento de Junin': '胡寧薩米恩托',
    'Sportivo Las Parejas': '拉斯帕雷哈斯體育',
    'Villa Dalmine': '達爾米內別墅',
    # === Chile Primera Division ===
    'Colo Colo': '高路高路',
    'Universidad de Chile': '智利大學',
    'Universidad Catolica': '天主教大學',
    'Universidad Católica': '天主教大學',
    'U. Catolica': '天主教大學',
    'Universidad de Concepcion': '康塞普森大學',
    'Universidad de Concepción': '康塞普森大學',
    'Palestino': '巴勒斯坦人',
    'Huachipato': '侯治柏度',
    "O'Higgins": '奧希金斯',
    'Everton de Vina del Mar': '維拿迪馬愛華頓',
    'Everton Vina del Mar': '維拿迪馬愛華頓',
    'Union Espanola': '西班牙聯盟',
    'Unión Española': '西班牙聯盟',
    'Audax Italiano': '奧達斯意大利人',
    'Cobresal': '科布雷索',
    'Nublense': '紐柏萊斯',
    'Ñublense': '紐柏萊斯',
    'Curico Unido': '庫里科聯',
    'Curicó Unido': '庫里科聯',
    'Coquimbo Unido': '科金博',
    'Coquimbo': '科金博',
    'La Serena': '拉塞雷納',
    'Deportes La Serena': '拉塞雷納',
    'Antofagasta': '安托法加斯塔',
    'Deportes Antofagasta': '安托法加斯塔',
    'Santiago Wanderers': '聖地亞哥漫遊者',
    'Deportes Temuco': '特木科體育',
    'Deportes Iquique': '伊基克體育',
    'Iquique': '伊基克體育',
    'Universidad de Catolica': '天主教大學',
    'Union La Calera': '卡拉雷聯',
    'Unión La Calera': '卡拉雷聯',
    'Everton CD': '維拿迪馬愛華頓',
    'Magallanes': '麥哲倫',
    'Deportes Copiapo': '科皮亞波體育',
    'Copiapo': '科皮亞波體育',
    'Barnechea': '巴尼奇亞',
    'San Luis de Quillota': '基約塔聖路易斯',
    'San Luis': '基約塔聖路易斯',
    'Santiago Morning': '聖地亞哥晨報',
    'Deportes Concepcion': '康塞普森體育',
    'Rangers de Talca': '塔爾卡遊騎兵',
    'Deportes Valdivia': '瓦爾迪維亞體育',
    'Deportes Puerto Montt': '蒙特港體育',
    'Deportes Melipilla': '梅利普拉體育',
    'Deportes Santa Cruz': '聖克魯斯體育',
    # === Mexico Liga MX ===
    'Club America': '阿美利加',
    'América': '阿美利加',
    'America': '阿美利加',
    'CF America': '阿美利加',
    'Guadalajara': '瓜達拉哈拉',
    'Chivas': '瓜達拉哈拉',
    'Cruz Azul': '藍十字',
    'Pumas UNAM': '普馬斯',
    'UNAM': '普馬斯',
    'Pumas': '普馬斯',
    'Monterrey': '蒙特雷',
    'CF Monterrey': '蒙特雷',
    'Tigres UANL': '堤格雷斯',
    'UANL': '堤格雷斯',
    'Tigres': '堤格雷斯',
    'Toluca': '托盧卡',
    'Deportivo Toluca': '托盧卡',
    'Santos Laguna': '拿根亞',
    'Santos': '拿根亞',
    'Leon': '萊昂',
    'León': '萊昂',
    'Club Leon': '萊昂',
    'Pachuca': '帕丘卡',
    'CF Pachuca': '帕丘卡',
    'Puebla': '普埃布拉',
    'Club Puebla': '普埃布拉',
    'Queretaro': '克雷塔羅',
    'Querétaro': '克雷塔羅',
    'Atlas': '阿特拿斯',
    'Club Atlas': '阿特拿斯',
    'Tijuana': '迪祖亞拿',
    'Club Tijuana': '迪祖亞拿',
    'Mazatlan': '馬薩特蘭',
    'Mazatlán': '馬薩特蘭',
    'Necaxa': '尼卡沙',
    'Club Necaxa': '尼卡沙',
    'FC Juarez': '祖亞雷斯',
    'Juárez': '祖亞雷斯',
    'Juarez': '祖亞雷斯',
    'Atletico San Luis': '聖路易斯競技',
    'Atlético San Luis': '聖路易斯競技',
    'San Luis': '聖路易斯競技',
    'Dorados de Sinaloa': '錫那羅亞金槍魚',
    'Mineros de Zacatecas': '薩卡特卡斯礦工',
    'Correcaminos UAT': 'UAT自動機',
    'Tampico Madero': '坦皮科馬德羅',
    'Celaya': '塞拉亞',
    'Zacatepec': '薩卡特佩克',
    'Oaxaca': '瓦哈卡',
    'Alebrijes Oaxaca': '瓦哈卡羊怪',
    'Venados FC': '維納多斯',
    'Cancun FC': '坎昆',
    'Tapatio': '塔帕蒂奧',
    'CD Tapatio': '塔帕蒂奧',
    'Alebrijes': '瓦哈卡羊怪',
    'Atlante': '阿特蘭特',
    'Potros UAEM': 'UAEM小馬',
    'Loros de Colima': '科利馬鸚鵡',
    'Tuxtla FC': '圖斯特拉',
    'Irapuato': '伊拉普阿托',
    'Leones Negros': '黑獅',
    'Universidad de Guadalajara': '瓜達拉哈拉大學',
    'UdeG': '瓜達拉哈拉大學',
    # === USA MLS ===
    'LA Galaxy': '洛杉磯銀河',
    'Los Angeles Galaxy': '洛杉磯銀河',
    'Los Angeles FC': '洛杉磯FC',
    'LAFC': '洛杉磯FC',
    'Seattle Sounders': '西雅圖海灣者',
    'Seattle Sounders FC': '西雅圖海灣者',
    'Portland Timbers': '波特蘭伐木者',
    'Portland': '波特蘭伐木者',
    'Vancouver Whitecaps': '溫哥華白帽',
    'Vancouver Whitecaps FC': '溫哥華白帽',
    'Vancouver': '溫哥華白帽',
    'Toronto FC': '多倫多FC',
    'Toronto': '多倫多FC',
    'CF Montreal': 'CF蒙特利爾',
    'Montreal Impact': '蒙特利爾衝擊',
    'Montreal': 'CF蒙特利爾',
    'New York City FC': '紐約城',
    'NYCFC': '紐約城',
    'New York Red Bulls': '紐約紅牛',
    'NY Red Bulls': '紐約紅牛',
    'Atlanta United': '阿特蘭大聯',
    'Atlanta United FC': '阿特蘭大聯',
    'Atlanta': '阿特蘭大聯',
    'Inter Miami CF': '國際邁亞密',
    'Inter Miami': '國際邁亞密',
    'Orlando City': '奧蘭多城',
    'Orlando City SC': '奧蘭多城',
    'Orlando': '奧蘭多城',
    'Columbus Crew': '哥倫布機員',
    'Columbus': '哥倫布機員',
    'FC Cincinnati': '辛辛那提FC',
    'Cincinnati': '辛辛那提FC',
    'DC United': '華盛頓聯隊',
    'D.C. United': '華盛頓聯隊',
    'Chicago Fire': '芝加哥火燄',
    'Chicago': '芝加哥火燄',
    'Houston Dynamo': '侯斯頓戴拿模',
    'Houston': '侯斯頓戴拿模',
    'FC Dallas': '達拉斯FC',
    'Dallas': '達拉斯FC',
    'Austin FC': '奧斯汀FC',
    'Austin': '奧斯汀FC',
    'Nashville SC': '拿舒維爾SC',
    'Nashville': '拿舒維爾SC',
    'Minnesota United': '明尼蘇達聯',
    'Minnesota United FC': '明尼蘇達聯',
    'Minnesota': '明尼蘇達聯',
    'Sporting Kansas City': '肯薩斯體育會',
    'Sporting KC': '肯薩斯體育會',
    'Kansas City': '肯薩斯體育會',
    'Real Salt Lake': '皇家鹽湖城',
    'Salt Lake': '皇家鹽湖城',
    'Colorado Rapids': '科羅拉多急流',
    'Colorado': '科羅拉多急流',
    'San Jose Earthquakes': '聖荷西地震',
    'San Jose': '聖荷西地震',
    'Philadelphia Union': '費城聯',
    'Philadelphia': '費城聯',
    'New England Revolution': '新英倫革命',
    'New England': '新英倫革命',
    'Charlotte FC': '夏洛特FC',
    'Charlotte': '夏洛特FC',
    'St. Louis City SC': '聖路易斯城',
    'St. Louis City': '聖路易斯城',
    'FC Cincinnati': '辛辛那提FC',
    'New York RB': '紐約紅牛',
    # === K League 1 ===
    'FC Seoul': 'FC首爾',
    'Seoul': 'FC首爾',
    'Jeonbuk Hyundai Motors': '全北現代',
    'Jeonbuk Hyundai': '全北現代',
    'Jeonbuk': '全北現代',
    'Ulsan Hyundai': '蔚山現代',
    'Ulsan HD': '蔚山HD',
    'Ulsan': '蔚山HD',
    'Pohang Steelers': '浦項製鐵',
    'Pohang': '浦項製鐵',
    'Suwon Samsung Bluewings': '水原三星藍翼',
    'Suwon Bluewings': '水原三星藍翼',
    'Suwon FC': '水原FC',
    'Jeju United': '濟州聯',
    'Jeju': '濟州聯',
    'Gangwon FC': '江原FC',
    'Gangwon': '江原FC',
    'Incheon United': '仁川聯',
    'Incheon': '仁川聯',
    'Daegu FC': '大邱FC',
    'Daegu': '大邱FC',
    'Gimcheon Sangmu': '金泉尚武',
    'Gimcheon': '金泉尚武',
    'Daejeon Hana Citizen': '大田市民',
    'Daejeon Citizen': '大田市民',
    'Daejeon': '大田市民',
    'Seongnam FC': '城南FC',
    'Seongnam': '城南FC',
    'Gwangju FC': '光州FC',
    'Gwangju': '光州FC',
    'FC Anyang': '安養FC',
    'Anyang': '安養FC',
    # === J League 1 ===
    'Kashima Antlers': '鹿島鹿角',
    'Kashima': '鹿島鹿角',
    'Urawa Red Diamonds': '浦和紅鑽',
    'Urawa Reds': '浦和紅鑽',
    'Urawa': '浦和紅鑽',
    'Kawasaki Frontale': '川崎前鋒',
    'Kawasaki': '川崎前鋒',
    'Yokohama F. Marinos': '橫濱水手',
    'Yokohama F Marinos': '橫濱水手',
    'Yokohama Marinos': '橫濱水手',
    'Yokohama FC': '橫濱FC',
    'Yokohama': '橫濱水手',
    'Gamba Osaka': '大阪飛腳',
    'G Osaka': '大阪飛腳',
    'Cerezo Osaka': '大阪櫻花',
    'C Osaka': '大阪櫻花',
    'Vissel Kobe': '神戶勝利船',
    'Kobe': '神戶勝利船',
    'Sanfrecce Hiroshima': '廣島三箭',
    'Hiroshima': '廣島三箭',
    'FC Tokyo': 'FC東京',
    'Tokyo': 'FC東京',
    'Tokyo Verdy': '東京綠茵',
    'Verdy': '東京綠茵',
    'Kashiwa Reysol': '柏雷素爾',
    'Kashiwa': '柏雷素爾',
    'Nagoya Grampus': '名古屋鯨魚',
    'Nagoya': '名古屋鯨魚',
    'Shimizu S-Pulse': '清水心跳',
    'Shimizu': '清水心跳',
    'Jubilo Iwata': '磐田山葉',
    'Iwata': '磐田山葉',
    'Shonan Bellmare': '湘南比馬',
    'Shonan': '湘南比馬',
    'Sagan Tosu': '鳥棲沙岩',
    'Tosu': '鳥棲沙岩',
    'Avispa Fukuoka': '福岡黃蜂',
    'Fukuoka': '福岡黃蜂',
    'Hokkaido Consadole Sapporo': '札幌岡薩多',
    'Consadole Sapporo': '札幌岡薩多',
    'Sapporo': '札幌岡薩多',
    'Oita Trinita': '大分三神',
    'Oita': '大分三神',
    'Vegalta Sendai': '仙台維加泰',
    'Sendai': '仙台維加泰',
    'Kyoto Sanga': '京都不死鳥',
    'Kyoto': '京都不死鳥',
    'Albirex Niigata': '新潟天鵝',
    'Niigata': '新潟天鵝',
    'V-Varen Nagasaki': '長崎成功丸',
    'Nagasaki': '長崎成功丸',
    'Omiya Ardija': '大宮松鼠',
    'Omiya': '大宮松鼠',
    'Montedio Yamagata': '山形山神',
    'Yamagata': '山形山神',
    'FC Machida Zelvia': '町田澤維亞',
    'Machida Zelvia': '町田澤維亞',
    'Machida': '町田澤維亞',
    'Kagoshima United': '鹿兒島聯',
    'Kagoshima': '鹿兒島聯',
    'Zweigen Kanazawa': '金澤薩維根',
    'Kanazawa': '金澤薩維根',
    'Mito HollyHock': '水戶蜀葵',
    'Mito': '水戶蜀葵',
    'Ventforet Kofu': '甲府風林',
    'Kofu': '甲府風林',
    'Yokohama SCC': '橫濱體育',
    'Tegevajaro Miyazaki': '宮崎鶴彥',
    'Iwaki FC': '磐城FC',
    'Iwaki': '磐城FC',
    'Fujieda MYFC': '藤枝MYFC',
    'Fujieda': '藤枝MYFC',
    'Gainare Tottori': '鳥取飛翔',
    'Tottori': '鳥取飛翔',
    'SC Sagamihara': '相模原體育',
    'Sagamihara': '相模原體育',
    'YSCC Yokohama': '橫濱YSCC',
    'Kataller Toyama': '富山勝利',
    'Toyama': '富山勝利',
    'Fukushima United': '福島聯',
    'Fukushima': '福島聯',
    'Vanraure Hachinohe': '八戶雲羅里',
    'Hachinohe': '八戶雲羅里',
    'AC Nagano Parceiro': '長野帕塞羅',
    'Nagano': '長野帕塞羅',
    'Azul Claro Numazu': '沼津青藍',
    'Numazu': '沼津青藍',
    'Blaublitz Akita': '秋田藍閃電',
    'Akita': '秋田藍閃電',
    'Matsumoto Yamaga': '松本山雅',
    'Matsumoto': '松本山雅',
    'Ehime FC': '愛媛FC',
    'Ehime': '愛媛FC',
    'Renofa Yamaguchi': '山口雷法',
    'Yamaguchi': '山口雷法',
    'Tokushima Vortis': '德島漩渦',
    'Tokushima': '德島漩渦',
    'FC Ryukyu': '琉球FC',
    'Ryukyu': '琉球FC',
    'Grulla Morioka': '盛岡仙鶴',
    'Morioka': '盛岡仙鶴',
    # === DB (football-data.co.uk) short names -> zh ===
    'For Sittard': '幸運薛達',
    'Nijmegen': '奈梅亨',
    'Graafschap': '迪加史卓普',
    'Den Haag': '海牙',
    'VVV Venlo': '芬洛',
    'Telstar': '泰斯達',
    'FC Emmen': '安曼',
    'AZ Alkmaar': '艾克馬亞',
    'Standard': '標準列治',
    'St. Gilloise': '聖基萊斯聯',
    'Waregem': '威爾郡',
    'Beerschot VA': '比斯查',
    'Oostende': '奧斯坦德',
    'Seraing': '塞萊恩',
    'Lommel SK': '洛默爾',
    'RAAL La Louviere': '拉盧維耶爾',
    'RWD Molenbeek': '莫倫貝克',
    'Beveren': '比華倫',
    'Waasland-Beveren': '華斯蘭比華倫',
    'Lokeren': '洛格倫',
    'Mouscron': '穆斯克龍',
    'Man City': '曼城',
    'Man United': '曼聯',
    'Newcastle': '紐卡素',
    "Nott'm Forest": '諾定咸森林',
    'West Ham': '韋斯咸',
    'Wolves': '狼隊',
    'Sheffield United': '錫菲聯',
    'Sheffield Weds': '錫周三',
    'Stoke': '史篤城',
    'Derby': '打比郡',
    'Peterboro': '彼德堡',
    'Wrexham': '域斯咸',
    'Wycombe': '韋甘比',
    'Lincoln': '林肯城',
    'Blackpool': '黑池',
    'Bolton': '保頓',
    'Barnsley': '班士利',
    'Huddersfield': '哈特斯菲',
    'Reading': '雷丁',
    'QPR': '昆士柏流浪',
    'Portsmouth': '樸茨茅夫',
    'Middlesbrough': '米杜士堡',
    'Millwall': '米禾爾',
    'Blackburn': '布力般流浪',
    'Bristol City': '布里斯托城',
    'Cardiff': '卡迪夫城',
    'Charlton': '查爾頓',
    'Coventry': '高雲地利',
    'Hull': '侯城',
    'Luton': '盧頓',
    'Norwich': '諾域治',
    'Oxford': '牛津聯',
    'Plymouth': '普利茅夫',
    'Preston': '普雷斯頓',
    'Rotherham': '洛達咸',
    'Sunderland': '新特蘭',
    'Swansea': '史雲斯',
    'Watford': '屈福特',
    'West Brom': '西布朗',
    'Wigan': '韋根',
    'Ipswich': '葉士域治',
    'Leeds': '列斯聯',
    'Leicester': '李斯特城',
    'Aston Villa': '阿士東維拉',
    'Bournemouth': '般尼茅夫',
    'Brentford': '賓福特',
    'Burnley': '般尼',
    'Arsenal': '阿仙奴',
    'Chelsea': '車路士',
    'Crystal Palace': '水晶宮',
    'Everton': '愛華頓',
    'Fulham': '富咸',
    'Liverpool': '利物浦',
    'Southampton': '修咸頓',
    'Tottenham': '熱刺',
    'Brighton': '白禮頓',
    'Huddersfield': '哈特斯菲',
    'Bayern Munich': '拜仁慕尼黑',
    'Dortmund': '多蒙特',
    'Leverkusen': '利華古遜',
    'Ein Frankfurt': '法蘭克福',
    "M'gladbach": '慕遜加柏',
    'Hertha': '哈化柏林',
    'FC Koln': '科隆',
    'Mainz': '緬恩斯',
    'St Pauli': '聖保利',
    'Hamburg': '漢堡',
    'Bielefeld': '比勒費爾德',
    'Darmstadt': '達斯泰特',
    'Greuther Furth': '格雷特霍夫',
    'Hannover': '漢諾威',
    'Heidenheim': '海登咸',
    'Hoffenheim': '賀芬咸',
    'Nurnberg': '紐倫堡',
    'Paderborn': '柏達邦',
    'Schalke 04': '史浩克零四',
    'Stuttgart': '史特加',
    'Union Berlin': '柏林聯',
    'Werder Bremen': '雲達不萊梅',
    'Augsburg': '奧格斯堡',
    'Elversberg': '艾華斯堡',
    'Fortuna Dusseldorf': '杜塞爾多夫',
    'Karlsruhe': '卡爾斯魯厄',
    'Kaiserslautern': '凱沙羅頓',
    'Magdeburg': '馬德堡',
    'Hansa Rostock': '羅斯托克',
    'Osnabruck': '奧斯納貝克',
    'Ulm': '烏爾姆',
    'Braunschweig': '布倫瑞克',
    'Preußen Münster': '普斯魯士明斯特',
    'Cottbus': '科特布斯',
    'Dresden': '特雷斯登',
    'Duisburg': '杜伊斯堡',
    'Erzgebirge Aue': '奧厄',
    'Ingolstadt': '因戈爾施塔特',
    'Regensburg': '雷根斯堡',
    'Sandhausen': '辛特侯遜',
    'Wurzburger Kickers': '維爾茨堡踢球者',
    'Athletico-PR': '巴拉納體育會',
    'Atletico-MG': '明尼路',
    'Atletico GO': '戈亞尼恩斯',
    'Botafogo RJ': '保地花高',
    'Flamengo RJ': '法林明高',
    'Chapecoense-SC': '查比高恩斯',
    'Vasco': '華斯高',
    'Remo': '雷莫',
    'Argentinos Jrs': '小阿根廷人',
    'Atl. Tucuman': '圖庫曼競技',
    'Central Cordoba': '科爾多瓦中央',
    'Dep. Riestra': '列斯特拉體育',
    'Estudiantes L.P.': '學生隊',
    'Gimnasia L.P.': '甘拿斯亞',
    'Gimnasia Mendoza': '門多薩體操',
    'Ind. Rivadavia': '里瓦達維亞獨立',
    'Newells Old Boys': '紐維爾舊生',
    'San Martin S.J.': '聖馬丁聖胡安',
    'Sarmiento Junin': '胡寧薩米恩托',
    'Talleres Cordoba': '泰拿尼斯',
    'Union de Santa Fe': '聖達菲聯',
    'Velez Sarsfield': '沙士菲',
    'Racing Club': '競賽會',
    'River Plate': '河床',
    'Boca Juniors': '小保加',
    'Independiente': '獨立隊',
    'San Lorenzo': '聖羅倫素',
    'Rosario Central': '羅沙里奧中央',
    'Belgrano': '貝格拉諾',
    'Banfield': '班菲特',
    'Huracan': '颶風隊',
    'Lanus': '拉努斯',
    'Platense': '普拉騰斯',
    'Tigre': '堤格雷',
    'Instituto': '體育學院',
    'Godoy Cruz': '葛度爾古斯',
    'Defensa y Justicia': '防衛者',
    'Aldosivi': '阿度斯維',
    'Barracas Central': '巴拉斯卡中央',
    'Atl. San Luis': '聖路易斯競技',
    'Club America': '阿美利加',
    'Club Leon': '萊昂',
    'Club Tijuana': '迪祖亞拿',
    'Guadalajara Chivas': '瓜達拉哈拉',
    'Juarez': '祖亞雷斯',
    'Mazatlan FC': '馬薩特蘭',
    'UNAM Pumas': '普馬斯',
    'Cruz Azul': '藍十字',
    'Tigres UANL': '堤格雷斯',
    'Toluca': '托盧卡',
    'Pachuca': '帕丘卡',
    'Puebla': '普埃布拉',
    'Queretaro': '克雷塔羅',
    'Necaxa': '尼卡沙',
    'Santos Laguna': '拿根亞',
    'Atlas': '阿特拿斯',
    'Atlante': '阿特蘭特',
    'Atlanta Utd': '阿特蘭大聯',
    'New York City': '紐約城',
    'Los Angeles Galaxy': '洛杉磯銀河',
    'Los Angeles FC': '洛杉磯FC',
    'DC United': '華盛頓聯隊',
    'Chicago Fire': '芝加哥火燄',
    'Houston Dynamo': '侯斯頓戴拿模',
    'FC Dallas': '達拉斯FC',
    'Austin FC': '奧斯汀FC',
    'Nashville SC': '拿舒維爾SC',
    'Minnesota United': '明尼蘇達聯',
    'Sporting Kansas City': '肯薩斯體育會',
    'Real Salt Lake': '皇家鹽湖城',
    'Colorado Rapids': '科羅拉多急流',
    'San Jose Earthquakes': '聖荷西地震',
    'Philadelphia Union': '費城聯',
    'New England Revolution': '新英倫革命',
    'St. Louis City': '聖路易斯城',
    'Toronto FC': '多倫多FC',
    'Vancouver Whitecaps': '溫哥華白帽',
    'Seattle Sounders': '西雅圖海灣者',
    'Portland Timbers': '波特蘭伐木者',
    'New York Red Bulls': '紐約紅牛',
    'CF Montreal': 'CF蒙特利爾',
    'Columbus Crew': '哥倫布機員',
    'FC Cincinnati': '辛辛那提FC',
    'Orlando City': '奧蘭多城',
    'Inter Miami': '國際邁亞密',
    'San Diego FC': '聖地亞哥FC',
    'Charlotte': '夏洛特FC',
    'Iwata': '磐田山葉',
    'Kyoto': '京都不死鳥',
    'Machida': '町田澤維亞',
    'Mito': '水戶蜀葵',
    'Chiba': '千葉市原',
    'Okayama': '岡山綠雉',
    'Verdy': '東京綠茵',
    'Urawa Reds': '浦和紅鑽',
    'FC Tokyo': 'FC東京',
    'America MG': '阿美利加明尼路',
    'CSA': 'CSA',
    'Figueirense': '費古倫斯',
    'Joinville': '祖恩維爾',
    'Parana': '帕拉拿',
    'Portuguesa': '葡萄牙人',
    'Santa Cruz': '聖塔克魯茲',
    'Atl. Rafaela': '拉斐拉競技',
    'Colon Santa FE': '聖達菲高隆',
    'Colon Santa Fe': '聖達菲高隆',
    'Estudiantes Rio Cuarto': '學生隊里奧誇爾托',
    'Olimpo Bahia Blanca': '巴伊亞布蘭卡奧林普',
    'San Martin T.': '聖馬丁圖庫曼',
    'Chiapas': '恰帕斯',
    'Lobos BUAP': 'BUAP狼',
    'Monarcas': '莫雷利亞',
    'Veracruz': '維拉克魯茲',
    'Chivas USA': '美國芝華士',
    'Kumamoto': '熊本深紅',
    'Yamaga': '松本山雅',
}


def translate_team_short(name):
    """Translate short team name to Traditional Chinese."""
    return TEAM_SHORT_ZH.get(name, name)


# Map The Odds API short names -> DB (football-data.co.uk) team names
ODDS_TO_DB = {
    'Paris Saint Germain': 'Paris SG',
    'AS Monaco': 'Monaco',
    'RC Lens': 'Lens',
    'Stade de Reims': 'Reims',
    'Saint Etienne': 'St Etienne',
    'Saint-Etienne': 'St Etienne',
    'Athletic Club': 'Ath Bilbao',
    'Athletic Bilbao': 'Ath Bilbao',
    'Atletico Madrid': 'Ath Madrid',
    'Atlético Madrid': 'Ath Madrid',
    'Celta Vigo': 'Celta',
    'Celta de Vigo': 'Celta',
    'Espanyol': 'Espanol',
    'RCD Espanyol': 'Espanol',
    'Rayo Vallecano': 'Vallecano',
    'Real Sociedad': 'Sociedad',
    'Real Sociedad B': 'Sociedad B',
    'Sporting Gijon': 'Sp Gijon',
    'Sporting Gijón': 'Sp Gijon',
    'Deportivo La Coruna': 'La Coruna',
    'Deportivo La Coruña': 'La Coruna',
    'Racing Santander': 'Santander',
    'Real Racing Club de Santander': 'Santander',
    'Real Oviedo': 'Oviedo',
    'Celta Fortuna': 'Celta B',
    'Sevilla FC': 'Sevilla',
    'Valencia CF': 'Valencia',
    'Villarreal CF': 'Villarreal',
    'Getafe CF': 'Getafe',
    'Girona FC': 'Girona',
    'Granada CF': 'Granada',
    'CA Osasuna': 'Osasuna',
    'Osasuna': 'Osasuna',
    'RCD Mallorca': 'Mallorca',
    'UD Las Palmas': 'Las Palmas',
    'Real Valladolid': 'Valladolid',
    'Real Valladolid CF': 'Valladolid',
    'CD Leganes': 'Leganes',
    'Leganés': 'Leganes',
    'Deportivo Alaves': 'Alaves',
    'Alavés': 'Alaves',
    'Elche CF': 'Elche',
    'Levante UD': 'Levante',
    'Malaga CF': 'Malaga',
    'Málaga': 'Malaga',
    'Real Madrid CF': 'Real Madrid',
    'FC Barcelona': 'Barcelona',
    'Real Betis': 'Betis',
    'Real Betis Balompié': 'Betis',
    'Real Zaragoza': 'Zaragoza',
    'Zaragoza': 'Zaragoza',
    'SD Eibar': 'Eibar',
    'CD Tenerife': 'Tenerife',
    'Tenerife': 'Tenerife',
    'SD Huesca': 'Huesca',
    'Huesca': 'Huesca',
    'Burgos CF': 'Burgos',
    'Burgos': 'Burgos',
    'Cordoba CF': 'Cordoba',
    'Córdoba': 'Cordoba',
    'CD Eldense': 'Eldense',
    'Eldense': 'Eldense',
    'CD Castellon': 'Castellon',
    'CD Castellón': 'Castellon',
    'Castellon': 'Castellon',
    'CE Sabadell FC': 'Sabadell',
    'Sabadell FC': 'Sabadell',
    'Sabadell': 'Sabadell',
    'UD Almeria': 'Almeria',
    'Almería': 'Almeria',
    'Almeria': 'Almeria',
    'AD Alcorcon': 'Alcorcon',
    'AD Alcorcón': 'Alcorcon',
    'Alcorcon': 'Alcorcon',
    'Albacete': 'Albacete',
    'CD Mirandes': 'Mirandes',
    'CD Mirandés': 'Mirandes',
    'Mirandes': 'Mirandes',
    'FC Cartagena': 'Cartagena',
    'Cartagena': 'Cartagena',
    'CD Numancia': 'Numancia',
    'Numancia': 'Numancia',
    'AD Ceuta FC': 'Ceuta',
    'Andorra CF': 'Andorra',
    'Andorra': 'Andorra',
    'USL Dunkerque': 'Dunkerque',
    'Dunkerque': 'Dunkerque',
    'Stade Lavallois': 'Laval',
    'Laval': 'Laval',
    'Pau FC': 'Pau FC',
    'Pau': 'Pau FC',
    'Paris': 'Paris FC',
    'Red Star': 'Red Star',
    'Red Star FC': 'Red Star',
    'Quevilly Rouen': 'Quevilly Rouen',
    'AC Ajaccio': 'Ajaccio',
    'Ajaccio': 'Ajaccio',
    'SC Bastia': 'Bastia',
    'Bastia': 'Bastia',
    'FC Metz': 'Metz',
    'Metz': 'Metz',
    'SM Caen': 'Caen',
    'Caen': 'Caen',
    'Grenoble Foot': 'Grenoble',
    'Grenoble': 'Grenoble',
    'EA Guingamp': 'Guingamp',
    'Guingamp': 'Guingamp',
    'FC Sochaux': 'Sochaux',
    'Sochaux': 'Sochaux',
    'AS Nancy': 'Nancy',
    'Nancy': 'Nancy',
    'Rodez AF': 'Rodez',
    'Rodez': 'Rodez',
    'Amiens SC': 'Amiens',
    'Amiens': 'Amiens',
    'Annecy FC': 'Annecy',
    'Annecy': 'Annecy',
    'US Concarneau': 'Concarneau',
    'Concarneau': 'Concarneau',
    'Paris FC': 'Paris FC',
    'ESTAC Troyes': 'Troyes',
    'Troyes': 'Troyes',
    'AJ Auxerre': 'Auxerre',
    'Auxerre': 'Auxerre',
    'Angers SCO': 'Angers',
    'Angers': 'Angers',
    'FC Girondins Bordeaux': 'Bordeaux',
    'Bordeaux': 'Bordeaux',
    'Dijon FCO': 'Dijon',
    'Dijon': 'Dijon',
    'Clermont Foot': 'Clermont',
    'Clermont': 'Clermont',
    'Le Mans FC': 'Le Mans',
    'RC Strasbourg': 'Strasbourg',
    'Strasbourg': 'Strasbourg',
    ' Toulouse FC': 'Toulouse',
    'Toulouse FC': 'Toulouse',
    'FC Lorient': 'Lorient',
    'FC Nantes': 'Nantes',
    'Montpellier HSC': 'Montpellier',
    'Stade Brestois': 'Brest',
    'Brest': 'Brest',
    'Le Havre AC': 'Le Havre',
    'OGC Nice': 'Nice',
    'Lille OSC': 'Lille',
    'Lyon': 'Lyon',
    'Olympique Lyonnais': 'Lyon',
    'Olympique de Marseille': 'Marseille',
    'Marseille': 'Marseille',
    'Stade Rennais': 'Rennes',
    'Rennes': 'Rennes',
    'Boulogne': 'Boulogne',
    # === Eredivisie (CSV names) ===
    'Fortuna Sittard': 'For Sittard',
    'NEC Nijmegen': 'Nijmegen',
    'NEC': 'Nijmegen',
    'De Graafschap': 'Graafschap',
    'ADO Den Haag': 'Den Haag',
    'FC Twente': 'Twente',
    'FC Utrecht': 'Utrecht',
    'SC Heerenveen': 'Heerenveen',
    'FC Groningen': 'Groningen',
    'FC Volendam': 'Volendam',
    'RKC Waalwijk': 'Waalwijk',
    'PEC Zwolle': 'Zwolle',
    'VVV-Venlo': 'VVV Venlo',
    'AZ': 'AZ Alkmaar',
    # === Belgium Pro (CSV names) ===
    'Standard Liege': 'Standard',
    'Standard Liège': 'Standard',
    'Union Saint-Gilloise': 'St. Gilloise',
    'Union SG': 'St. Gilloise',
    'Royale Union SG': 'St. Gilloise',
    'Zulte Waregem': 'Waregem',
    'Beerschot': 'Beerschot VA',
    'KAS Eupen': 'Eupen',
    'KV Kortrijk': 'Kortrijk',
    'KV Mechelen': 'Mechelen',
    'Sporting Charleroi': 'Charleroi',
    'OH Leuven': 'Oud-Heverlee Leuven',
    'KRC Genk': 'Genk',
    'KAA Gent': 'Gent',
    'Royal Antwerp': 'Antwerp',
    'Club Bruges': 'Club Brugge',
    # === England (CSV names) ===
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Newcastle United': 'Newcastle',
    'Nottingham Forest': "Nott'm Forest",
    'West Ham United': 'West Ham',
    'Wolverhampton Wanderers': 'Wolves',
    'Leeds United': 'Leeds',
    'Leicester City': 'Leicester',
    'Norwich City': 'Norwich',
    'Luton Town': 'Luton',
    'Ipswich Town': 'Ipswich',
    'West Bromwich Albion': 'West Brom',
    'Hull City': 'Hull',
    'Coventry City': 'Coventry',
    'Stoke City': 'Stoke',
    'Derby County': 'Derby',
    'Sheffield Wednesday': 'Sheffield Weds',
    'Sheff Wed': 'Sheffield Weds',
    'Peterborough United': 'Peterboro',
    'Peterborough': 'Peterboro',
    'Blackburn Rovers': 'Blackburn',
    'Charlton Athletic': 'Charlton',
    'Oxford United': 'Oxford',
    'Plymouth Argyle': 'Plymouth',
    'Preston North End': 'Preston',
    'Rotherham United': 'Rotherham',
    'Swansea City': 'Swansea',
    'Wigan Athletic': 'Wigan',
    'Wycombe Wanderers': 'Wycombe',
    'Bolton Wanderers': 'Bolton',
    'Huddersfield Town': 'Huddersfield',
    'Lincoln City': 'Lincoln',
    'Queens Park Rangers': 'QPR',
    'Tottenham Hotspur': 'Tottenham',
    'Cardiff City': 'Cardiff',
    # === Germany (CSV names) ===
    'Eintracht Frankfurt': 'Ein Frankfurt',
    'Frankfurt': 'Ein Frankfurt',
    'Borussia Monchengladbach': "M'gladbach",
    'Borussia Mönchengladbach': "M'gladbach",
    "Borussia M'Gladbach": "M'gladbach",
    'Gladbach': "M'gladbach",
    'Hertha BSC': 'Hertha',
    'Hertha Berlin': 'Hertha',
    '1. FC Koln': 'FC Koln',
    'Köln': 'FC Koln',
    '1. FC Köln': 'FC Koln',
    'FSV Mainz 05': 'Mainz',
    'Mainz 05': 'Mainz',
    'FC St. Pauli': 'St Pauli',
    'St. Pauli': 'St Pauli',
    'Hamburger SV': 'Hamburg',
    'Arminia Bielefeld': 'Bielefeld',
    'VfL Bochum': 'Bochum',
    'SV Darmstadt 98': 'Darmstadt',
    'Borussia Dortmund': 'Dortmund',
    'SpVgg Greuther Furth': 'Greuther Furth',
    'Greuther Fürth': 'Greuther Furth',
    'Hannover 96': 'Hannover',
    '1. FC Heidenheim': 'Heidenheim',
    'TSG Hoffenheim': 'Hoffenheim',
    'Bayer Leverkusen': 'Leverkusen',
    '1. FC Nurnberg': 'Nurnberg',
    'Nürnberg': 'Nurnberg',
    'SC Paderborn 07': 'Paderborn',
    'Leipzig': 'RB Leipzig',
    'FC Schalke 04': 'Schalke 04',
    'Schalke': 'Schalke 04',
    'VfB Stuttgart': 'Stuttgart',
    'FC Union Berlin': 'Union Berlin',
    'VfL Wolfsburg': 'Wolfsburg',
    'FC Augsburg': 'Augsburg',
    'SC Freiburg': 'Freiburg',
    'SV Elversberg': 'Elversberg',
    'Fortuna Dusseldorf': 'Fortuna Dusseldorf',
    'Fortuna Düsseldorf': 'Fortuna Dusseldorf',
    'Karlsruher SC': 'Karlsruhe',
    '1. FC Kaiserslautern': 'Kaiserslautern',
    '1. FC Magdeburg': 'Magdeburg',
    'Hansa Rostock': 'Hansa Rostock',
    'Rostock': 'Hansa Rostock',
    'VfL Osnabruck': 'Osnabruck',
    'Osnabrück': 'Osnabruck',
    'SV Wehen Wiesbaden': 'Wehen',
    'SSV Ulm 1846': 'Ulm',
    'Eintracht Braunschweig': 'Braunschweig',
    'Preussen Munster': 'Preußen Münster',
    'Energie Cottbus': 'Cottbus',
    'Dynamo Dresden': 'Dresden',
    'MSV Duisburg': 'Duisburg',
    'FC Ingolstadt': 'Ingolstadt',
    'SSV Jahn Regensburg': 'Regensburg',
    'SV Sandhausen': 'Sandhausen',
    'Würzburger Kickers': 'Wurzburger Kickers',
    # === Brazil (CSV names) ===
    'Athletico Paranaense': 'Athletico-PR',
    'Atletico Paranaense': 'Athletico-PR',
    'Atletico Mineiro': 'Atletico-MG',
    'Atlético Mineiro': 'Atletico-MG',
    'Atletico Goianiense': 'Atletico GO',
    'Atlético Goianiense': 'Atletico GO',
    'Botafogo': 'Botafogo RJ',
    'Flamengo': 'Flamengo RJ',
    'Chapecoense': 'Chapecoense-SC',
    'Vasco da Gama': 'Vasco',
    'Ceará': 'Ceara',
    'São Paulo': 'Sao Paulo',
    'Grêmio': 'Gremio',
    'Cuiabá': 'Cuiaba',
    'Criciúma': 'Criciuma',
    'Vitória': 'Vitoria',
    'Red Bull Bragantino': 'Bragantino',
    'RB Bragantino': 'Bragantino',
    # === Argentina (CSV names) ===
    'Argentinos Juniors': 'Argentinos Jrs',
    'Atletico Tucuman': 'Atl. Tucuman',
    'Atlético Tucumán': 'Atl. Tucuman',
    'Central Córdoba': 'Central Cordoba',
    'Deportivo Riestra': 'Dep. Riestra',
    'Estudiantes LP': 'Estudiantes L.P.',
    'Estudiantes': 'Estudiantes L.P.',
    'Gimnasia LP': 'Gimnasia L.P.',
    'Gimnasia': 'Gimnasia L.P.',
    "Newell's Old Boys": 'Newells Old Boys',
    'Independiente Rivadavia': 'Ind. Rivadavia',
    'San Martin de San Juan': 'San Martin S.J.',
    'Sarmiento': 'Sarmiento Junin',
    'Talleres': 'Talleres Cordoba',
    'Union Santa Fe': 'Union de Santa Fe',
    'Unión Santa Fe': 'Union de Santa Fe',
    'Vélez Sarsfield': 'Velez Sarsfield',
    'Atlético Tucumán' if False else 'Godoy Cruz': 'Godoy Cruz',
    # === Mexico (CSV names) ===
    'Atletico San Luis': 'Atl. San Luis',
    'Atlético San Luis': 'Atl. San Luis',
    'America': 'Club America',
    'América': 'Club America',
    'CF America': 'Club America',
    'Leon': 'Club Leon',
    'León': 'Club Leon',
    'Tijuana': 'Club Tijuana',
    'Guadalajara': 'Guadalajara Chivas',
    'Chivas': 'Guadalajara Chivas',
    'FC Juarez': 'Juarez',
    'Juárez': 'Juarez',
    'Mazatlan': 'Mazatlan FC',
    'Mazatlán': 'Mazatlan FC',
    'Pumas UNAM': 'UNAM Pumas',
    'UNAM': 'UNAM Pumas',
    'Pumas': 'UNAM Pumas',
    'UANL': 'Tigres UANL',
    'Tigres': 'Tigres UANL',
    'CF Monterrey': 'Monterrey',
    'Club Necaxa': 'Necaxa',
    'CF Pachuca': 'Pachuca',
    'Club Puebla': 'Puebla',
    'Querétaro': 'Queretaro',
    'Deportivo Toluca': 'Toluca',
    'Club Atlas': 'Atlas',
    # === USA MLS (CSV names) ===
    'Atlanta United': 'Atlanta Utd',
    'Atlanta United FC': 'Atlanta Utd',
    'New York City FC': 'New York City',
    'NYCFC': 'New York City',
    'LA Galaxy': 'Los Angeles Galaxy',
    'LAFC': 'Los Angeles FC',
    'Charlotte FC': 'Charlotte',
    'D.C. United': 'DC United',
    'Inter Miami CF': 'Inter Miami',
    'Orlando City SC': 'Orlando City',
    'Cincinnati': 'FC Cincinnati',
    'Dallas': 'FC Dallas',
    'Nashville': 'Nashville SC',
    'Minnesota United FC': 'Minnesota United',
    'Sporting KC': 'Sporting Kansas City',
    'Vancouver Whitecaps FC': 'Vancouver Whitecaps',
    'Seattle Sounders FC': 'Seattle Sounders',
    'NY Red Bulls': 'New York Red Bulls',
    'Montreal Impact': 'CF Montreal',
    # === J League (CSV names) ===
    'Jubilo Iwata': 'Iwata',
    'Kyoto Sanga': 'Kyoto',
    'FC Machida Zelvia': 'Machida',
    'Machida Zelvia': 'Machida',
    'Mito HollyHock': 'Mito',
    'JEF United Chiba': 'Chiba',
    'JEF Chiba': 'Chiba',
    'Fagiano Okayama': 'Okayama',
    'Tokyo Verdy': 'Verdy',
    'Urawa Red Diamonds': 'Urawa Reds',
    'Consadole Sapporo': 'Hokkaido Consadole Sapporo',
}


def db_team_name(odds_name):
    """Map The Odds API team name to DB (football-data.co.uk) name."""
    return ODDS_TO_DB.get(odds_name, odds_name)


# Reverse map: DB name -> Traditional Chinese (built once)
_DB_TO_ZH = {}
for _odds_name, _zh in TEAM_SHORT_ZH.items():
    _DB_TO_ZH.setdefault(db_team_name(_odds_name), _zh)


def db_team_to_zh(db_name):
    """Translate a DB (football-data.co.uk) team name to Traditional Chinese."""
    return _DB_TO_ZH.get(db_name, db_name)


def translate_league(code):
    """Translate league code to Traditional Chinese."""
    return LEAGUE_NAMES_ZH.get(code, code)


def init_live_odds_table():
    """Create live_odds table if not exists."""
    conn = get_connection()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS live_odds (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            league TEXT,
            match_date TEXT,
            match_time TEXT,
            home_team TEXT,
            away_team TEXT,
            home_team_en TEXT,
            away_team_en TEXT,
            ah_line REAL,
            ah_home_odds REAL,
            ah_away_odds REAL,
            ou_line REAL,
            over_odds REAL,
            under_odds REAL,
            bookmaker TEXT,
            commence_time TEXT,
            fetched_at TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(league, home_team_en, away_team_en, commence_time)
        )
    """)
    conn.commit()
    conn.close()


def extract_odds_from_match(match_data, preferred_bookmaker='bet365'):
    """
    Extract AH line and O/U line from a match's bookmaker data.
    Tries preferred bookmaker first, falls back to any available.
    Returns dict with odds or None.
    """
    bookmakers = match_data.get('bookmakers', [])
    if not bookmakers:
        return None

    # Sort to prioritize preferred bookmaker
    sorted_bms = sorted(
        bookmakers,
        key=lambda b: 0 if b.get('key') == preferred_bookmaker else 1
    )

    for bm in sorted_bms:
        markets = {m['key']: m for m in bm.get('markets', [])}
        spreads = markets.get('spreads', {})
        totals = markets.get('totals', {})

        ah_line = None
        ah_home = None
        ah_away = None
        ou_line = None
        over_odds = None
        under_odds = None

        # Extract Asian Handicap (spreads)
        for outcome in spreads.get('outcomes', []):
            name = outcome.get('name', '')
            point = outcome.get('point')
            price = outcome.get('price')
            home_team = match_data.get('home_team', '')

            if name == home_team:
                ah_line = point
                ah_home = price
            else:
                ah_away = price

        # Extract Over/Under (totals)
        for outcome in totals.get('outcomes', []):
            name = outcome.get('name', '')
            point = outcome.get('point')
            price = outcome.get('price')

            if name == 'Over':
                ou_line = point
                over_odds = price
            elif name == 'Under':
                under_odds = price

        # If we got AH data, use this bookmaker
        if ah_line is not None:
            return {
                'ah_line': ah_line,
                'ah_home_odds': ah_home,
                'ah_away_odds': ah_away,
                'ou_line': ou_line,
                'over_odds': over_odds,
                'under_odds': under_odds,
                'bookmaker': bm.get('title', bm.get('key', 'unknown')),
            }

    return None


def fetch_odds_for_league(league_code):
    """
    Fetch odds for a single league from The Odds API.
    Returns list of match dicts with odds.
    """
    if not ODDS_API_KEY:
        print(f"[Odds] No API key configured")
        return []

    sport_key = LEAGUE_TO_SPORT.get(league_code)
    if not sport_key:
        return []

    url = f"{ODDS_BASE_URL}/sports/{sport_key}/odds"
    params = {
        'apiKey': ODDS_API_KEY,
        'regions': 'eu,uk',
        'markets': 'spreads,totals',
        'bookmakers': 'bet365,pinnacle',
        'dateFormat': 'iso',
    }

    try:
        resp = requests.get(url, params=params, timeout=30)
        remaining = resp.headers.get('x-requests-remaining', 'N/A')
        print(f"[Odds] {league_code}: status={resp.status_code}, remaining={remaining}")

        if resp.status_code != 200:
            print(f"[Odds] Error: {resp.text[:200]}")
            return []

        data = resp.json()
        matches = []

        for m in data:
            odds = extract_odds_from_match(m)
            if not odds:
                continue

            commence = m.get('commence_time', '')
            match_date = commence[:10] if commence else ''
            match_time = commence[11:16] if len(commence) > 16 else ''

            home_en = m.get('home_team', '')
            away_en = m.get('away_team', '')

            matches.append({
                'league': league_code,
                'league_name': translate_league(league_code),
                'match_date': match_date,
                'match_time': match_time,
                'home_team': translate_team_short(home_en),
                'away_team': translate_team_short(away_en),
                'home_team_en': home_en,
                'away_team_en': away_en,
                'ah_line': odds['ah_line'],
                'ah_home_odds': odds['ah_home_odds'],
                'ah_away_odds': odds['ah_away_odds'],
                'ou_line': odds['ou_line'],
                'over_odds': odds['over_odds'],
                'under_odds': odds['under_odds'],
                'bookmaker': odds['bookmaker'],
                'commence_time': commence,
                'source': 'the-odds-api',
            })

        return matches

    except Exception as e:
        print(f"[Odds] Exception fetching {league_code}: {e}")
        return []


def fetch_all_odds(leagues=None):
    """
    Fetch odds for supported leagues and store in database.
    leagues: optional list of league codes to fetch (rotation for quota).
    """
    init_live_odds_table()
    all_matches = []

    league_list = leagues if leagues else list(LEAGUE_TO_SPORT.keys())
    for league_code in league_list:
        matches = fetch_odds_for_league(league_code)
        all_matches.extend(matches)

    # Store in database
    conn = get_connection()
    for m in all_matches:
        conn.execute("""
            INSERT OR REPLACE INTO live_odds
            (league, match_date, match_time, home_team, away_team,
             home_team_en, away_team_en,
             ah_line, ah_home_odds, ah_away_odds,
             ou_line, over_odds, under_odds,
             bookmaker, commence_time, fetched_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
        """, (
            m['league'], m['match_date'], m['match_time'],
            m['home_team'], m['away_team'],
            m['home_team_en'], m['away_team_en'],
            m['ah_line'], m['ah_home_odds'], m['ah_away_odds'],
            m['ou_line'], m['over_odds'], m['under_odds'],
            m['bookmaker'], m['commence_time']
        ))
    conn.commit()
    conn.close()

    print(f"[Odds] Stored {len(all_matches)} matches with live odds")
    return all_matches


def get_live_odds_for_date(target_date, league=None):
    """
    Get live odds matches for a specific date.
    Returns list of match dicts.
    """
    conn = get_connection()
    query = """
        SELECT * FROM live_odds
        WHERE match_date = ?
    """
    params = [target_date]
    if league:
        query += " AND league = ?"
        params.append(league)
    query += " ORDER BY match_time"

    rows = conn.execute(query, params).fetchall()
    conn.close()

    result = []
    for r in rows:
        result.append({
            'id': f"live_{r['id']}",
            'league': r['league'],
            'league_name': translate_league(r['league']),
            'match_date': r['match_date'],
            'match_time': r['match_time'] or '',
            'home_team': r['home_team'],
            'away_team': r['away_team'],
            'ah_line': r['ah_line'],
            'ah_home_odds': r['ah_home_odds'],
            'ah_away_odds': r['ah_away_odds'],
            'ou_line': r['ou_line'],
            'over_odds': r['over_odds'],
            'under_odds': r['under_odds'],
            'bookmaker': r['bookmaker'],
            'source': 'live_odds',
        })
    return result


if __name__ == '__main__':
    print("Testing odds fetcher...")
    matches = fetch_all_odds()
    print(f"\nTotal matches fetched: {len(matches)}")
    for m in matches[:5]:
        print(f"  {m['match_date']} {m['match_time']} | {m['league_name']} | "
              f"{m['home_team']} vs {m['away_team']} | "
              f"AH: {m['ah_line']} ({m['ah_home_odds']}/{m['ah_away_odds']}) | "
              f"O/U: {m['ou_line']} ({m['over_odds']}/{m['under_odds']}) | "
              f"{m['bookmaker']}")
